# Generated by rake
# DO NOT EDIT THIS FILE DIRECTLY
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{postgresql_schema}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sven G. Broenstrup"]
  s.date = %q{2011-03-05}
  s.description = %q{Use PostgreSQL schemas for storing different Rails environments.}
  s.email = %q{info@spom.net}
  s.files = ["lib/postgresql_schema.rb", "lib/tasks/postgresql_schema.rake", "VERSION", "README.rdoc", "LICENCE", "Gemfile"]
  s.homepage = %q{http://spom.net/}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.0}
  s.summary = %q{Use PostgreSQL schemas for storing different Rails environments.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.0.0"])
      s.add_runtime_dependency(%q<pg>, [">= 0.10.1"])
    else
      s.add_dependency(%q<rails>, [">= 3.0.0"])
      s.add_dependency(%q<pg>, [">= 0.10.1"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.0.0"])
    s.add_dependency(%q<pg>, [">= 0.10.1"])
  end
end
